// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: "TWITTER KEY",
  TWITTER_CONSUMER_SECRET: "TWITTER SECRET",
  TWITTER_ACCESS_TOKEN: "TWITTER TOEKN",
  TWITTER_TOKEN_SECRET: "TOKEN SECRET"
};

const GOOGLE_TOKEN={
  GOOGLE_CLIENT_ID : 'GOOGLE CLIENT ID',
  GOOGLE_CLIENT_SECRET:'GOOGLE SECRET'
}

const DB_USER = "SOME USERNAME";
const DB_PASSWORD = "SOME PASSWPORD";
const MONGODB = {
  MONGODB_URI: `mongodb://localhost/oauth`
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...MONGODB,
  ...SESSION,
  ...GOOGLE_TOKEN
};

module.exports = KEYS;
